// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: control.proto

package controlv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModelControl_ListModels_FullMethodName  = "/control.v1.ModelControl/ListModels"
	ModelControl_GetModel_FullMethodName    = "/control.v1.ModelControl/GetModel"
	ModelControl_LoadModel_FullMethodName   = "/control.v1.ModelControl/LoadModel"
	ModelControl_UnloadModel_FullMethodName = "/control.v1.ModelControl/UnloadModel"
	ModelControl_ReloadModel_FullMethodName = "/control.v1.ModelControl/ReloadModel"
)

// ModelControlClient is the client API for ModelControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModelControlClient interface {
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	GetModel(ctx context.Context, in *GetModelRequest, opts ...grpc.CallOption) (*Model, error)
	LoadModel(ctx context.Context, in *LoadModelRequest, opts ...grpc.CallOption) (*Model, error)
	UnloadModel(ctx context.Context, in *UnloadModelRequest, opts ...grpc.CallOption) (*Model, error)
	ReloadModel(ctx context.Context, in *ReloadModelRequest, opts ...grpc.CallOption) (*Model, error)
}

type modelControlClient struct {
	cc grpc.ClientConnInterface
}

func NewModelControlClient(cc grpc.ClientConnInterface) ModelControlClient {
	return &modelControlClient{cc}
}

func (c *modelControlClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, ModelControl_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelControlClient) GetModel(ctx context.Context, in *GetModelRequest, opts ...grpc.CallOption) (*Model, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Model)
	err := c.cc.Invoke(ctx, ModelControl_GetModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelControlClient) LoadModel(ctx context.Context, in *LoadModelRequest, opts ...grpc.CallOption) (*Model, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Model)
	err := c.cc.Invoke(ctx, ModelControl_LoadModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelControlClient) UnloadModel(ctx context.Context, in *UnloadModelRequest, opts ...grpc.CallOption) (*Model, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Model)
	err := c.cc.Invoke(ctx, ModelControl_UnloadModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelControlClient) ReloadModel(ctx context.Context, in *ReloadModelRequest, opts ...grpc.CallOption) (*Model, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Model)
	err := c.cc.Invoke(ctx, ModelControl_ReloadModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelControlServer is the server API for ModelControl service.
// All implementations must embed UnimplementedModelControlServer
// for forward compatibility.
type ModelControlServer interface {
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	GetModel(context.Context, *GetModelRequest) (*Model, error)
	LoadModel(context.Context, *LoadModelRequest) (*Model, error)
	UnloadModel(context.Context, *UnloadModelRequest) (*Model, error)
	ReloadModel(context.Context, *ReloadModelRequest) (*Model, error)
	mustEmbedUnimplementedModelControlServer()
}

// UnimplementedModelControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModelControlServer struct{}

func (UnimplementedModelControlServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedModelControlServer) GetModel(context.Context, *GetModelRequest) (*Model, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModel not implemented")
}
func (UnimplementedModelControlServer) LoadModel(context.Context, *LoadModelRequest) (*Model, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadModel not implemented")
}
func (UnimplementedModelControlServer) UnloadModel(context.Context, *UnloadModelRequest) (*Model, error) {
	return nil, status.Error(codes.Unimplemented, "method UnloadModel not implemented")
}
func (UnimplementedModelControlServer) ReloadModel(context.Context, *ReloadModelRequest) (*Model, error) {
	return nil, status.Error(codes.Unimplemented, "method ReloadModel not implemented")
}
func (UnimplementedModelControlServer) mustEmbedUnimplementedModelControlServer() {}
func (UnimplementedModelControlServer) testEmbeddedByValue()                      {}

// UnsafeModelControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelControlServer will
// result in compilation errors.
type UnsafeModelControlServer interface {
	mustEmbedUnimplementedModelControlServer()
}

func RegisterModelControlServer(s grpc.ServiceRegistrar, srv ModelControlServer) {
	// If the following call panics, it indicates UnimplementedModelControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModelControl_ServiceDesc, srv)
}

func _ModelControl_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelControlServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelControl_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelControlServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelControl_GetModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelControlServer).GetModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelControl_GetModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelControlServer).GetModel(ctx, req.(*GetModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelControl_LoadModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelControlServer).LoadModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelControl_LoadModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelControlServer).LoadModel(ctx, req.(*LoadModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelControl_UnloadModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnloadModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelControlServer).UnloadModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelControl_UnloadModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelControlServer).UnloadModel(ctx, req.(*UnloadModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelControl_ReloadModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelControlServer).ReloadModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelControl_ReloadModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelControlServer).ReloadModel(ctx, req.(*ReloadModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModelControl_ServiceDesc is the grpc.ServiceDesc for ModelControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModelControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "control.v1.ModelControl",
	HandlerType: (*ModelControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListModels",
			Handler:    _ModelControl_ListModels_Handler,
		},
		{
			MethodName: "GetModel",
			Handler:    _ModelControl_GetModel_Handler,
		},
		{
			MethodName: "LoadModel",
			Handler:    _ModelControl_LoadModel_Handler,
		},
		{
			MethodName: "UnloadModel",
			Handler:    _ModelControl_UnloadModel_Handler,
		},
		{
			MethodName: "ReloadModel",
			Handler:    _ModelControl_ReloadModel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "control.proto",
}

const (
	BackendControl_ListBackends_FullMethodName = "/control.v1.BackendControl/ListBackends"
	BackendControl_GetBackend_FullMethodName   = "/control.v1.BackendControl/GetBackend"
	BackendControl_Health_FullMethodName       = "/control.v1.BackendControl/Health"
)

// BackendControlClient is the client API for BackendControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BackendControlClient interface {
	ListBackends(ctx context.Context, in *ListBackendsRequest, opts ...grpc.CallOption) (*ListBackendsResponse, error)
	GetBackend(ctx context.Context, in *GetBackendRequest, opts ...grpc.CallOption) (*Backend, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type backendControlClient struct {
	cc grpc.ClientConnInterface
}

func NewBackendControlClient(cc grpc.ClientConnInterface) BackendControlClient {
	return &backendControlClient{cc}
}

func (c *backendControlClient) ListBackends(ctx context.Context, in *ListBackendsRequest, opts ...grpc.CallOption) (*ListBackendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBackendsResponse)
	err := c.cc.Invoke(ctx, BackendControl_ListBackends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendControlClient) GetBackend(ctx context.Context, in *GetBackendRequest, opts ...grpc.CallOption) (*Backend, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Backend)
	err := c.cc.Invoke(ctx, BackendControl_GetBackend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendControlClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, BackendControl_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackendControlServer is the server API for BackendControl service.
// All implementations must embed UnimplementedBackendControlServer
// for forward compatibility.
type BackendControlServer interface {
	ListBackends(context.Context, *ListBackendsRequest) (*ListBackendsResponse, error)
	GetBackend(context.Context, *GetBackendRequest) (*Backend, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedBackendControlServer()
}

// UnimplementedBackendControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBackendControlServer struct{}

func (UnimplementedBackendControlServer) ListBackends(context.Context, *ListBackendsRequest) (*ListBackendsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBackends not implemented")
}
func (UnimplementedBackendControlServer) GetBackend(context.Context, *GetBackendRequest) (*Backend, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBackend not implemented")
}
func (UnimplementedBackendControlServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedBackendControlServer) mustEmbedUnimplementedBackendControlServer() {}
func (UnimplementedBackendControlServer) testEmbeddedByValue()                        {}

// UnsafeBackendControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackendControlServer will
// result in compilation errors.
type UnsafeBackendControlServer interface {
	mustEmbedUnimplementedBackendControlServer()
}

func RegisterBackendControlServer(s grpc.ServiceRegistrar, srv BackendControlServer) {
	// If the following call panics, it indicates UnimplementedBackendControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BackendControl_ServiceDesc, srv)
}

func _BackendControl_ListBackends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBackendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendControlServer).ListBackends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendControl_ListBackends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendControlServer).ListBackends(ctx, req.(*ListBackendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendControl_GetBackend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBackendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendControlServer).GetBackend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendControl_GetBackend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendControlServer).GetBackend(ctx, req.(*GetBackendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendControl_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendControlServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendControl_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendControlServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BackendControl_ServiceDesc is the grpc.ServiceDesc for BackendControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BackendControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "control.v1.BackendControl",
	HandlerType: (*BackendControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBackends",
			Handler:    _BackendControl_ListBackends_Handler,
		},
		{
			MethodName: "GetBackend",
			Handler:    _BackendControl_GetBackend_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _BackendControl_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "control.proto",
}
