// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: control.proto

package controlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Model struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Frontend      string                 `protobuf:"bytes,2,opt,name=frontend,proto3" json:"frontend,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Purpose       string                 `protobuf:"bytes,4,opt,name=purpose,proto3" json:"purpose,omitempty"`
	NativeId      string                 `protobuf:"bytes,5,opt,name=native_id,json=nativeId,proto3" json:"native_id,omitempty"`
	DesiredState  string                 `protobuf:"bytes,6,opt,name=desired_state,json=desiredState,proto3" json:"desired_state,omitempty"`
	ObservedState string                 `protobuf:"bytes,7,opt,name=observed_state,json=observedState,proto3" json:"observed_state,omitempty"`
	SocketPath    *string                `protobuf:"bytes,8,opt,name=socket_path,json=socketPath,proto3,oneof" json:"socket_path,omitempty"` // unset for mlxlm
	LastError     string                 `protobuf:"bytes,9,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	Pid           *int64                 `protobuf:"varint,10,opt,name=pid,proto3,oneof" json:"pid,omitempty"`                           // unset when unloaded
	MemoryMb      *int64                 `protobuf:"varint,11,opt,name=memory_mb,json=memoryMb,proto3,oneof" json:"memory_mb,omitempty"` // theoretical; unset when unloaded
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

func (x *Model) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Model) GetFrontend() string {
	if x != nil {
		return x.Frontend
	}
	return ""
}

func (x *Model) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Model) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *Model) GetNativeId() string {
	if x != nil {
		return x.NativeId
	}
	return ""
}

func (x *Model) GetDesiredState() string {
	if x != nil {
		return x.DesiredState
	}
	return ""
}

func (x *Model) GetObservedState() string {
	if x != nil {
		return x.ObservedState
	}
	return ""
}

func (x *Model) GetSocketPath() string {
	if x != nil && x.SocketPath != nil {
		return *x.SocketPath
	}
	return ""
}

func (x *Model) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *Model) GetPid() int64 {
	if x != nil && x.Pid != nil {
		return *x.Pid
	}
	return 0
}

func (x *Model) GetMemoryMb() int64 {
	if x != nil && x.MemoryMb != nil {
		return *x.MemoryMb
	}
	return 0
}

type Backend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	SocketPath    *string                `protobuf:"bytes,2,opt,name=socket_path,json=socketPath,proto3,oneof" json:"socket_path,omitempty"` // unset for mlxlm
	ObservedState string                 `protobuf:"bytes,3,opt,name=observed_state,json=observedState,proto3" json:"observed_state,omitempty"`
	LastError     string                 `protobuf:"bytes,4,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	Ready         bool                   `protobuf:"varint,5,opt,name=ready,proto3" json:"ready,omitempty"`
	Pids          []int64                `protobuf:"varint,6,rep,packed,name=pids,proto3" json:"pids,omitempty"`                        // empty = none
	MemoryMb      *int64                 `protobuf:"varint,7,opt,name=memory_mb,json=memoryMb,proto3,oneof" json:"memory_mb,omitempty"` // latest sample; unset if none
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Backend) Reset() {
	*x = Backend{}
	mi := &file_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backend) ProtoMessage() {}

func (x *Backend) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backend.ProtoReflect.Descriptor instead.
func (*Backend) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *Backend) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Backend) GetSocketPath() string {
	if x != nil && x.SocketPath != nil {
		return *x.SocketPath
	}
	return ""
}

func (x *Backend) GetObservedState() string {
	if x != nil {
		return x.ObservedState
	}
	return ""
}

func (x *Backend) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *Backend) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *Backend) GetPids() []int64 {
	if x != nil {
		return x.Pids
	}
	return nil
}

func (x *Backend) GetMemoryMb() int64 {
	if x != nil && x.MemoryMb != nil {
		return *x.MemoryMb
	}
	return 0
}

type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*Model               `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{3}
}

func (x *ListModelsResponse) GetModels() []*Model {
	if x != nil {
		return x.Models
	}
	return nil
}

type GetModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelRequest) Reset() {
	*x = GetModelRequest{}
	mi := &file_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelRequest) ProtoMessage() {}

func (x *GetModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelRequest.ProtoReflect.Descriptor instead.
func (*GetModelRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{4}
}

func (x *GetModelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type LoadModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadModelRequest) Reset() {
	*x = LoadModelRequest{}
	mi := &file_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadModelRequest) ProtoMessage() {}

func (x *LoadModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadModelRequest.ProtoReflect.Descriptor instead.
func (*LoadModelRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{5}
}

func (x *LoadModelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UnloadModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadModelRequest) Reset() {
	*x = UnloadModelRequest{}
	mi := &file_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadModelRequest) ProtoMessage() {}

func (x *UnloadModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadModelRequest.ProtoReflect.Descriptor instead.
func (*UnloadModelRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{6}
}

func (x *UnloadModelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReloadModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadModelRequest) Reset() {
	*x = ReloadModelRequest{}
	mi := &file_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadModelRequest) ProtoMessage() {}

func (x *ReloadModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadModelRequest.ProtoReflect.Descriptor instead.
func (*ReloadModelRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{7}
}

func (x *ReloadModelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListBackendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackendsRequest) Reset() {
	*x = ListBackendsRequest{}
	mi := &file_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackendsRequest) ProtoMessage() {}

func (x *ListBackendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackendsRequest.ProtoReflect.Descriptor instead.
func (*ListBackendsRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{8}
}

type ListBackendsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backends      []*Backend             `protobuf:"bytes,1,rep,name=backends,proto3" json:"backends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackendsResponse) Reset() {
	*x = ListBackendsResponse{}
	mi := &file_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackendsResponse) ProtoMessage() {}

func (x *ListBackendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackendsResponse.ProtoReflect.Descriptor instead.
func (*ListBackendsResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{9}
}

func (x *ListBackendsResponse) GetBackends() []*Backend {
	if x != nil {
		return x.Backends
	}
	return nil
}

type GetBackendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBackendRequest) Reset() {
	*x = GetBackendRequest{}
	mi := &file_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackendRequest) ProtoMessage() {}

func (x *GetBackendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackendRequest.ProtoReflect.Descriptor instead.
func (*GetBackendRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{10}
}

func (x *GetBackendRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{11}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backends      []*Backend             `protobuf:"bytes,1,rep,name=backends,proto3" json:"backends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{12}
}

func (x *HealthResponse) GetBackends() []*Backend {
	if x != nil {
		return x.Backends
	}
	return nil
}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\n" +
	"control.v1\"\xee\x02\n" +
	"\x05Model\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bfrontend\x18\x02 \x01(\tR\bfrontend\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x18\n" +
	"\apurpose\x18\x04 \x01(\tR\apurpose\x12\x1b\n" +
	"\tnative_id\x18\x05 \x01(\tR\bnativeId\x12#\n" +
	"\rdesired_state\x18\x06 \x01(\tR\fdesiredState\x12%\n" +
	"\x0eobserved_state\x18\a \x01(\tR\robservedState\x12$\n" +
	"\vsocket_path\x18\b \x01(\tH\x00R\n" +
	"socketPath\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"last_error\x18\t \x01(\tR\tlastError\x12\x15\n" +
	"\x03pid\x18\n" +
	" \x01(\x03H\x01R\x03pid\x88\x01\x01\x12 \n" +
	"\tmemory_mb\x18\v \x01(\x03H\x02R\bmemoryMb\x88\x01\x01B\x0e\n" +
	"\f_socket_pathB\x06\n" +
	"\x04_pidB\f\n" +
	"\n" +
	"_memory_mb\"\xf3\x01\n" +
	"\aBackend\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12$\n" +
	"\vsocket_path\x18\x02 \x01(\tH\x00R\n" +
	"socketPath\x88\x01\x01\x12%\n" +
	"\x0eobserved_state\x18\x03 \x01(\tR\robservedState\x12\x1d\n" +
	"\n" +
	"last_error\x18\x04 \x01(\tR\tlastError\x12\x14\n" +
	"\x05ready\x18\x05 \x01(\bR\x05ready\x12\x12\n" +
	"\x04pids\x18\x06 \x03(\x03R\x04pids\x12 \n" +
	"\tmemory_mb\x18\a \x01(\x03H\x01R\bmemoryMb\x88\x01\x01B\x0e\n" +
	"\f_socket_pathB\f\n" +
	"\n" +
	"_memory_mb\"\x13\n" +
	"\x11ListModelsRequest\"?\n" +
	"\x12ListModelsResponse\x12)\n" +
	"\x06models\x18\x01 \x03(\v2\x11.control.v1.ModelR\x06models\"!\n" +
	"\x0fGetModelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\"\n" +
	"\x10LoadModelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"$\n" +
	"\x12UnloadModelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"$\n" +
	"\x12ReloadModelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13ListBackendsRequest\"G\n" +
	"\x14ListBackendsResponse\x12/\n" +
	"\bbackends\x18\x01 \x03(\v2\x13.control.v1.BackendR\bbackends\"'\n" +
	"\x11GetBackendRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\"\x0f\n" +
	"\rHealthRequest\"A\n" +
	"\x0eHealthResponse\x12/\n" +
	"\bbackends\x18\x01 \x03(\v2\x13.control.v1.BackendR\bbackends2\xd9\x02\n" +
	"\fModelControl\x12K\n" +
	"\n" +
	"ListModels\x12\x1d.control.v1.ListModelsRequest\x1a\x1e.control.v1.ListModelsResponse\x12:\n" +
	"\bGetModel\x12\x1b.control.v1.GetModelRequest\x1a\x11.control.v1.Model\x12<\n" +
	"\tLoadModel\x12\x1c.control.v1.LoadModelRequest\x1a\x11.control.v1.Model\x12@\n" +
	"\vUnloadModel\x12\x1e.control.v1.UnloadModelRequest\x1a\x11.control.v1.Model\x12@\n" +
	"\vReloadModel\x12\x1e.control.v1.ReloadModelRequest\x1a\x11.control.v1.Model2\xe6\x01\n" +
	"\x0eBackendControl\x12Q\n" +
	"\fListBackends\x12\x1f.control.v1.ListBackendsRequest\x1a .control.v1.ListBackendsResponse\x12@\n" +
	"\n" +
	"GetBackend\x12\x1d.control.v1.GetBackendRequest\x1a\x13.control.v1.Backend\x12?\n" +
	"\x06Health\x12\x19.control.v1.HealthRequest\x1a\x1a.control.v1.HealthResponseB$Z\"encore.app/control/proto/controlv1b\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_control_proto_goTypes = []any{
	(*Model)(nil),                // 0: control.v1.Model
	(*Backend)(nil),              // 1: control.v1.Backend
	(*ListModelsRequest)(nil),    // 2: control.v1.ListModelsRequest
	(*ListModelsResponse)(nil),   // 3: control.v1.ListModelsResponse
	(*GetModelRequest)(nil),      // 4: control.v1.GetModelRequest
	(*LoadModelRequest)(nil),     // 5: control.v1.LoadModelRequest
	(*UnloadModelRequest)(nil),   // 6: control.v1.UnloadModelRequest
	(*ReloadModelRequest)(nil),   // 7: control.v1.ReloadModelRequest
	(*ListBackendsRequest)(nil),  // 8: control.v1.ListBackendsRequest
	(*ListBackendsResponse)(nil), // 9: control.v1.ListBackendsResponse
	(*GetBackendRequest)(nil),    // 10: control.v1.GetBackendRequest
	(*HealthRequest)(nil),        // 11: control.v1.HealthRequest
	(*HealthResponse)(nil),       // 12: control.v1.HealthResponse
}
var file_control_proto_depIdxs = []int32{
	0,  // 0: control.v1.ListModelsResponse.models:type_name -> control.v1.Model
	1,  // 1: control.v1.ListBackendsResponse.backends:type_name -> control.v1.Backend
	1,  // 2: control.v1.HealthResponse.backends:type_name -> control.v1.Backend
	2,  // 3: control.v1.ModelControl.ListModels:input_type -> control.v1.ListModelsRequest
	4,  // 4: control.v1.ModelControl.GetModel:input_type -> control.v1.GetModelRequest
	5,  // 5: control.v1.ModelControl.LoadModel:input_type -> control.v1.LoadModelRequest
	6,  // 6: control.v1.ModelControl.UnloadModel:input_type -> control.v1.UnloadModelRequest
	7,  // 7: control.v1.ModelControl.ReloadModel:input_type -> control.v1.ReloadModelRequest
	8,  // 8: control.v1.BackendControl.ListBackends:input_type -> control.v1.ListBackendsRequest
	10, // 9: control.v1.BackendControl.GetBackend:input_type -> control.v1.GetBackendRequest
	11, // 10: control.v1.BackendControl.Health:input_type -> control.v1.HealthRequest
	3,  // 11: control.v1.ModelControl.ListModels:output_type -> control.v1.ListModelsResponse
	0,  // 12: control.v1.ModelControl.GetModel:output_type -> control.v1.Model
	0,  // 13: control.v1.ModelControl.LoadModel:output_type -> control.v1.Model
	0,  // 14: control.v1.ModelControl.UnloadModel:output_type -> control.v1.Model
	0,  // 15: control.v1.ModelControl.ReloadModel:output_type -> control.v1.Model
	9,  // 16: control.v1.BackendControl.ListBackends:output_type -> control.v1.ListBackendsResponse
	1,  // 17: control.v1.BackendControl.GetBackend:output_type -> control.v1.Backend
	12, // 18: control.v1.BackendControl.Health:output_type -> control.v1.HealthResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	file_control_proto_msgTypes[0].OneofWrappers = []any{}
	file_control_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
